services:
  database:
    container_name: postgres
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - cta_storage_volume:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - inner_coonection

  app:
    build:
      context: .
      args:
        PORT: ${PORT}
    depends_on:
      - database
    ports:
      - ${PORT}:${PORT}
    networks:
      - inner_coonection

volumes:
  cta_storage_volume:

networks:
  inner_coonection:
